### PR TITLE
Coverage badge: add support for the code-coverage-api plugin

### PR DESCRIPTION
**Pull request by rguenthe**
I added support for the code-coverage-api-plugin ([https://github.com/jenkinsci/code-coverage-api-plugin](https://github.com/jenkinsci/code-coverage-api-plugin))

Currently reports the line coverage percentage.

### CODE REVIEW

**Review by dorian-coygo — CHANGES_REQUESTED** [review]
Any chance you could write a simple test? 

Great work!

**Comment by rguenthe** [comment]
Thanks! I looked into the testDoCoverageIcon() function and found that it is not implemented yet (only a prototype). So no chance to simply extend some existing tests ...

Generally this should be implemented for all coverage sources but possibly should be a separate PR.

**Comment by SxMShaDoW** [comment]
Thanks for keeping the plugin alive :)

**Comment by rguenthe** [comment]
Seems like it broke compatibility with linux (including travis CI). Compling and packaging works fine but the tests crash! I develop mostly on windows and everything is fine there. 

I have no idea whats causing this. Must be something with the code-coverage-api dependency ... You may wish to revert the changes ...

This is the error im getting when invoking `mvn clean install` on a linux system (Ubuntu 18.04.3 LTS)

`Running org.jenkinsci.plugins.badge.PublicBadgeActionTest
Tests run: 10, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 49.209 sec <<< FAILURE! - in org.jenkinsci.plugins.badge.PublicBadgeActionTest
testGetIconFileName(org.jenkinsci.plugins.badge.PublicBadgeActionTest)  Time elapsed: 36.196 sec  <<< ERROR!
org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
        at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:269)
        at jenkins.InitReactorRunner.run(InitReactorRunner.java:44)
        at jenkins.model.Jenkins.executeReactor(Jenkins.java:916)
        at jenkins.model.Jenkins.<init>(Jenkins.java:815)
        at hudson.model.Hudson.<init>(Hudson.java:85)
        at org.jvnet.hudson.test.JenkinsRule.newHudson(JenkinsRule.java:566)
        at org.jvnet.hudson.test.JenkinsRule.before(JenkinsRule.java:353)
        at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:511)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:176)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:905)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:106)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:176)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:905)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866)
        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483)
        at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:404)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
        at java.util.Arrays.sort(Arrays.java:1312)
        at java.util.Arrays.sort(Arrays.java:1506)
        at java.util.ArrayList.sort(ArrayList.java:1462)
        at java.util.Collections.sort(Collections.java:143)
        at hudson.ExtensionList.sort(ExtensionList.java:369)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:289)
        at hudson.ExtensionList.getComponents(ExtensionList.java:167)
        at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:185)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
        at hudson.ExtensionList.iterator(ExtensionList.java:156)
        at jenkins.branch.CustomOrganizationFolderDescriptor.doAddSpecificDescriptors(CustomOrganizationFolderDescriptor.java:166)
        at jenkins.branch.CustomOrganizationFolderDescriptor.addSpecificDescriptors(CustomOrganizationFolderDescriptor.java:145)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:106)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:176)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:905)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by SxMShaDoW** [comment]
will look into it :/ . I didn't realize travis was causing issues because I haven't updated to Github Apps from webhooks :(

**Comment by SxMShaDoW** [comment]
It works locally for you? Can't even compile on linux anymore (probably because the jenkins version used here is so old). Did you change anything in your pom to get it to work @rguenthe

**Comment by SxMShaDoW** [comment]
fixed the compile error (old version of jenkins can't compile on java 11 so def need to look into bumping all the dependencies), so I at least got to the same error you are getting. did the tests ever work for you?

**Comment by SxMShaDoW** [comment]
reverted this until i can troubleshoot it more. the plugin seems to be very outdated :/

**Comment by rguenthe** [comment]
> It works locally for you? Can't even compile on linux anymore (probably because the jenkins version used here is so old). Did you change anything in your pom to get it to work @rguenthe

In the pom I only added the dependency to the code-coverage-api-plugin. Everything worked for me on Windows (even the tests passed) using oracle java version 1.8.0_40. The plugin also works fine on my local jenkins installation (2.190.1 and also Windows).

> reverted this until i can troubleshoot it more. the plugin seems to be very outdated :/

Thanks. Sorry I didnt see this coming :-(

**Comment by dorian-coygo** [comment]
Im going to create an issue about upgrading the plugin to at least 2.X and making it build on java 11. Once that gets us in a good place adding your code back will be very easy.

**Pull request merged**
